# Generated by Django 2.0.4 on 2018-06-30 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_follow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='follow',
            new_name='following',
        ),
    ]
